costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    filter_info_topic: "/costmap_filter_info"
    type: 0
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    #yaml_filename: "/home/kodama/TheConstruct/ros2_ws/src/deepmind_bot/deepmind_bot_navigation/maps/map_keepout.yaml"
    yaml_filename: "/home/simulations/ros2_sims_ws/src/theconstruct/deepmind_bot/deepmind_bot_navigation/maps/map_keepout.yaml"
